config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes_app.urls')),
    path('register', user_views.register, name="user-register"),
    path('login', auth_views.LoginView.as_view(template_name="users/login.html"), name="user-login"),
    path('logout', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="user-logout"),
    path('profile', user_views.profile, name="user-profile"),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes_app/urls.py
from django.urls import path
from . import views

'app/modle_viewtype'
'recipes_app/recipe_detail.html'


urlpatterns = [
    path('', views.RecipeListView.as_view(), name="recipes-home"),
    path('recipes/<int:pk>/', views.RecipeDetailView.as_view(), name="recipes-detail"),
    path('recipe/create/', views.RecipeCreateView.as_view(), name="recipes-create"),
    path('recipes/<int:pk>/update/', views.RecipeUpdateView.as_view(), name="recipes-update"),
    path('recipes/<int:pk>/delete/', views.RecipeDeleteView.as_view(), name="recipes-delete"),
    path('search/', views.RecipeSearchView.as_view(), name="search_recipes"),
    path('about/', views.about, name="recipes-about"),
    path('ingredient/<int:pk>/', views.IngredientDetailView.as_view(), name="ingredient-detail"),
    path('recipes/<int:pk>/favorite/', views.FavoriteRecipe, name="favorite-recipe"),
    path('recipes/<int:pk>/unfavorite/', views.UnfavoriteRecipe, name="unfavorite-recipe"),
    path('favorites/', views.UserFavoriteRecipes.as_view(), name="user-favorites"),
    path('add-category/', views.add_category, name='add-category'),
    path('recipes/', views.recipe_list_by_category, name='recipe-list-by-category'),
    

]

recipes_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.name

def get_default_category():
    return Category.objects.get_or_create(name="Smhack")[0].id



class Recipe(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(User, related_name='recipes', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='recipes/', null=True, blank=True)
    favorited_by = models.ManyToManyField(User, related_name='favorited_recipes', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=get_default_category)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
        return reverse("recipes-detail", kwargs={"pk": self.pk})
    

    def __str__(self):
        return self.title

class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    image_url = models.URLField(blank=True, null=True) 

    def __str__(self):
        return self.name

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=5, decimal_places=2)
    measurement = models.CharField(max_length=50)  # grams, cups, tablespoons

    def __str__(self):
        return f"{self.quantity} {self.measurement} of {self.ingredient.name} for {self.recipe.title}"

recipes_app/forms.py
from django import forms
from .models import Recipe, RecipeIngredient, Ingredient, Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description'] 
        
        
class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'category', 'image']


RecipeIngredientFormSet = forms.inlineformset_factory(
    Recipe, 
    RecipeIngredient, 
    fields=('ingredient', 'quantity', 'measurement'), 
    extra=1,
    widgets={
        'ingredient': forms.Select(attrs={'class': 'form-control'}),
        'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
        'measurement': forms.TextInput(attrs={'class': 'form-control'})
    }
)

recipes_app/views.py
from typing import Any
from django.db.models.query import QuerySet 
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Count


from .forms import RecipeForm, RecipeIngredientFormSet, CategoryForm

from django.urls import reverse_lazy

from . import models


# Create your views here.

class RecipeListView(ListView):
    model = models.Recipe
    template_name = 'recipes_app/home.html'
    context_object_name = 'recipes'


class RecipeDetailView(DetailView):
    model = models.Recipe


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = models.Recipe
    template_name = 'recipes_app/recipe_form.html'
    form_class = RecipeForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = RecipeIngredientFormSet(self.request.POST, prefix='ingredients')
        else:
            context['formset'] = RecipeIngredientFormSet(prefix='ingredients')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        form.instance.author = self.request.user

        if formset.is_valid():
            response = super().form_valid(form)
            
            formset.instance = self.object
            formset.save()
            
            return response
        else:
            return self.form_invalid(form)



class RecipeUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Recipe
    form_class = RecipeForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = RecipeIngredientFormSet(self.request.POST, instance=self.object, prefix='ingredients')
        else:
            context['formset'] = RecipeIngredientFormSet(instance=self.object, prefix='ingredients')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']

        if formset.is_valid():
            response = super().form_valid(form)
            
            formset.instance = self.object
            formset.save()
            
            return response
        else:
            return self.form_invalid(form)

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeDeleteView( LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Recipe
    success_url = reverse_lazy('recipes-home')
    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author

def about(request):
    
    return render(request,"recipes_app/about.html", {'title': 'About this app'})

def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        formset = RecipeIngredientFormSet(request.POST, prefix='ingredients')
        if form.is_valid() and formset.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            
            for ingredient_form in formset:
                # Set the recipe before saving the ingredient
                ingredient_instance = ingredient_form.save(commit=False)
                ingredient_instance.recipe = recipe
                ingredient_instance.save()
                
            return redirect('recipes-home')
    else:
        form = RecipeForm()
        formset = RecipeIngredientFormSet(prefix='ingredients')
    return render(request, 'recipe_form.html', {'form': form, 'formset': formset})



class IngredientDetailView(DetailView):
    model = models.Ingredient
    template_name = 'recipes_app/ingredient_detail.html'
    context_object_name = 'ingredient'



class RecipeSearchView(ListView):
    model = models.Recipe
    template_name = 'recipes_app/home.html'
    context_object_name = 'recipes'
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return self.model.objects.filter(
                Q(title__icontains=query) | 
                Q(recipeingredient__ingredient__name__icontains=query)
            ).distinct().order_by('-created_at')
        return self.model.objects.all().order_by('-created_at')
        
    def get_queryset(self):
        query = self.request.GET.get('q')
        return self.model.objects.filter(title__icontains=query).order_by('-created_at')
        


def FavoriteRecipe(request, pk):
    recipe = get_object_or_404(models.Recipe, pk=pk)
    if request.user not in recipe.favorited_by.all():
        recipe.favorited_by.add(request.user)
    return redirect(recipe.get_absolute_url())

def UnfavoriteRecipe(request, pk):
    recipe = get_object_or_404(models.Recipe, pk=pk)
    recipe.favorited_by.remove(request.user)
    return redirect(recipe.get_absolute_url())
    
class UserFavoriteRecipes(ListView):
    model = models.Recipe
    template_name = 'recipes_app/user_favorites.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        return self.request.user.favorited_recipes.all()   
    

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to a success page or dashboard after saving
            return redirect('dashboard')
    else:
        form = CategoryForm()

    context = {'form': form}
    return render(request, 'recipes_app/recipe_form.html', context)    

def recipe_list_by_category(request):
    category_name = request.GET.get('category')
    if category_name:
        category = models.Category.objects.get(name=category_name)
        recipes = models.Recipe.objects.filter(category=category)
    else:
        recipes = models.Recipe.objects.all()

    context = {
        'recipes': recipes
    }
    return render(request, 'recipes_app/home.html', context)

recipes_app/templates/recipes_app/about.html
{% extends 'recipes_app/base.html' %} {% block content %}


    <!-- start of banner -->


      <svg
        class="banner-shape-1"
        width="39"
        height="40"
        viewBox="0 0 39 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
        <path
          class="path"
          d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z"
        />
        <path
          d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
      </svg>

      <svg
        class="banner-shape-2"
        width="39"
        height="39"
        viewBox="0 0 39 39"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g filter="url(#filter0_d)">
          <path
            class="path"
            d="M24.1587 21.5623C30.02 21.3764 34.6209 16.4742 34.435 10.6128C34.2491 4.75147 29.3468 0.1506 23.4855 0.336498C17.6241 0.522396 13.0233 5.42466 13.2092 11.286C13.3951 17.1474 18.2973 21.7482 24.1587 21.5623Z"
          />
          <path
            d="M5.64626 20.0297C11.1568 19.9267 15.7407 24.2062 16.0362 29.6855L24.631 29.4616L24.1476 10.8081L5.41797 11.296L5.64626 20.0297Z"
            stroke="#040306"
            stroke-miterlimit="10"
          />
        </g>
        <defs>
          <filter
            id="filter0_d"
            x="0.905273"
            y="0"
            width="37.8663"
            height="38.1979"
            filterUnits="userSpaceOnUse"
            color-interpolation-filters="sRGB"
          >
            <feFlood flood-opacity="0" result="BackgroundImageFix" />
            <feColorMatrix
              in="SourceAlpha"
              type="matrix"
              values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            />
            <feOffset dy="4" />
            <feGaussianBlur stdDeviation="2" />
            <feColorMatrix
              type="matrix"
              values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"
            />
            <feBlend
              mode="normal"
              in2="BackgroundImageFix"
              result="effect1_dropShadow"
            />
            <feBlend
              mode="normal"
              in="SourceGraphic"
              in2="effect1_dropShadow"
              result="shape"
            />
          </filter>
        </defs>
      </svg>

      <svg
        class="banner-shape-3"
        width="39"
        height="40"
        viewBox="0 0 39 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
        <path
          class="path"
          d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z"
        />
        <path
          d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
      </svg>

      <svg
        class="banner-border"
        height="240"
        viewBox="0 0 2202 240"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M1 123.043C67.2858 167.865 259.022 257.325 549.762 188.784C764.181 125.427 967.75 112.601 1200.42 169.707C1347.76 205.869 1901.91 374.562 2201 1"
          stroke-width="2"
        />
      </svg>
    </div>

    <!-- end of banner -->  

<div class="container my-4">
  <div class="columns is-multiline">
    {% for recipe in recipes %}
    <div class="column is-4-widescreen is-6-desktop mb-5">
      <article class="card">
        <div class="card-image">
          <figure class="image is-4by3">
            <a href="{% url 'recipes-detail' recipe.pk %}">
            <img src="/media/{{ recipe.image }}" alt="Recipe Image">
            </a>
          </figure>
        </div>
        <div class="card-content">
          <h2 class="title is-4"><a href="{% url 'recipes-detail' recipe.pk %}">{{ recipe.title }}</a></h2>
          <h6 class="subtitle is-6">{{ recipe.author }} | {{ recipe.created_at }}</h6>
          <h5 class="title is-5 mt-3">Ingredients:</h5>
          <ul>
            {% for ingredient in recipe.recipeingredient_set.all %}
            <li>
              <strong>{{ ingredient.ingredient.name }}</strong>: {{ ingredient.quantity }} {{ ingredient.measurement }}
            </li>
            {% endfor %}
          </ul>
        </div>
        <footer class="card-footer">
          {% if user == recipe.author %}
          <a href="{% url 'recipes-update' recipe.pk %}" class="card-footer-item">Edit</a>
          <a href="{% url 'recipes-delete' recipe.pk %}" class="card-footer-item">Delete</a>
          {% endif %}
          <a href="{% url 'recipes-detail' recipe.pk %}" class="card-footer-item">View</a>
        </footer>
      </article>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

recipes_app/templates/recipes_app/category_form.html
{% extends 'recipes_app/base.html' %} 

{% block content %}

<section class="section">
  <div class="container">
    <h1 class="title">Add Category</h1>
    <div class="card">
      <header class="card-header">
        <p class="card-header-title">Category Form</p>
      </header>
      <div class="card-content">
        <form method="POST" action="{% url 'add-category' %}">
          {% csrf_token %}
          
          <div class="field">
            <label class="label">{{ form.name.label }}</label>
            <div class="control">
              {{ form.name }}
            </div>
          </div>

          <div class="field">
            <div class="control">
              <input type="submit" value="Add Category" class="button is-primary">
              <a class="button is-light" href="{% url 'dashboard' %}">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

recipes_app/templates/recipes_app/home.html
{% extends 'recipes_app/base.html' %} {% block content %}


    <!-- start of banner -->
    <div class="banner has-text-centered">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-9-widescreen">
            <h1 class="mb-6"> Find the perfect recipe.
            </h1>
            <ul class="widget-list-inline mb-4">
              <li class="list-inline-item"><a href="recipes/?category=American%20Soul">American Soul</a></li>
              <li class="list-inline-item"><a href="recipes/?category=Smhack">Smhack</a></li>
              <li class="list-inline-item"><a href="recipes/?category=Vegan">Vegan</a></li>
              <li class="list-inline-item"><a href="recipes/?category=Korean">Korean</a></li>
              <li class="list-inline-item"><a href="recipes/?category=Mexican">Mexican</a></li>
              <li class="list-inline-item"><a href="recipes/?category=Greek">Greek</a></li>
              <li class="list-inline-item"><a href="recipes/?category=BBQ">BBQ</a></li>
            </ul>
          </div>
        </div>
      </div>

      <svg
        class="banner-shape-1"
        width="39"
        height="40"
        viewBox="0 0 39 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
        <path
          class="path"
          d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z"
        />
        <path
          d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
      </svg>

      <svg
        class="banner-shape-2"
        width="39"
        height="39"
        viewBox="0 0 39 39"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g filter="url(#filter0_d)">
          <path
            class="path"
            d="M24.1587 21.5623C30.02 21.3764 34.6209 16.4742 34.435 10.6128C34.2491 4.75147 29.3468 0.1506 23.4855 0.336498C17.6241 0.522396 13.0233 5.42466 13.2092 11.286C13.3951 17.1474 18.2973 21.7482 24.1587 21.5623Z"
          />
          <path
            d="M5.64626 20.0297C11.1568 19.9267 15.7407 24.2062 16.0362 29.6855L24.631 29.4616L24.1476 10.8081L5.41797 11.296L5.64626 20.0297Z"
            stroke="#040306"
            stroke-miterlimit="10"
          />
        </g>
        <defs>
          <filter
            id="filter0_d"
            x="0.905273"
            y="0"
            width="37.8663"
            height="38.1979"
            filterUnits="userSpaceOnUse"
            color-interpolation-filters="sRGB"
          >
            <feFlood flood-opacity="0" result="BackgroundImageFix" />
            <feColorMatrix
              in="SourceAlpha"
              type="matrix"
              values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            />
            <feOffset dy="4" />
            <feGaussianBlur stdDeviation="2" />
            <feColorMatrix
              type="matrix"
              values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"
            />
            <feBlend
              mode="normal"
              in2="BackgroundImageFix"
              result="effect1_dropShadow"
            />
            <feBlend
              mode="normal"
              in="SourceGraphic"
              in2="effect1_dropShadow"
              result="shape"
            />
          </filter>
        </defs>
      </svg>

      <svg
        class="banner-shape-3"
        width="39"
        height="40"
        viewBox="0 0 39 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
        <path
          class="path"
          d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z"
        />
        <path
          d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z"
          stroke="#040306"
          stroke-miterlimit="10"
        />
      </svg>

      <svg
        class="banner-border"
        height="240"
        viewBox="0 0 2202 240"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M1 123.043C67.2858 167.865 259.022 257.325 549.762 188.784C764.181 125.427 967.75 112.601 1200.42 169.707C1347.76 205.869 1901.91 374.562 2201 1"
          stroke-width="2"
        />
      </svg>
    </div>

    <!-- end of banner -->  

<div class="container my-4">
  <div class="columns is-multiline">
    {% for recipe in recipes %}
    <div class="column is-4-widescreen is-6-desktop mb-5">
      <article class="card">
        <div class="card-image">
          <figure class="image is-4by3">
            <a href="{% url 'recipes-detail' recipe.pk %}">
            <img src="/media/{{ recipe.image }}" alt="Recipe Image">
            </a>
          </figure>
        </div>
        <div class="card-content">
          <h2 class="title is-4"><a href="{% url 'recipes-detail' recipe.pk %}">{{ recipe.title }}</a></h2>
          <h6 class="subtitle is-6">{{ recipe.author }} | {{ recipe.created_at }}</h6>
          <h5 class="title is-5 mt-3">Ingredients:</h5>
          <ul>
            {% for ingredient in recipe.recipeingredient_set.all %}
            <li>
              <strong>{{ ingredient.ingredient.name }}</strong>: {{ ingredient.quantity }} {{ ingredient.measurement }}
            </li>
            {% endfor %}
          </ul>
        </div>
        <footer class="card-footer">
          {% if user == recipe.author %}
          <a href="{% url 'recipes-update' recipe.pk %}" class="card-footer-item">Edit</a>
          <a href="{% url 'recipes-delete' recipe.pk %}" class="card-footer-item">Delete</a>
          {% endif %}
          <a href="{% url 'recipes-detail' recipe.pk %}" class="card-footer-item">View</a>
        </footer>
      </article>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}


 

recipes_app/templates/recipes_app/ingredient_detail.html
{% extends "recipes_app/base.html" %} 
{% block content %}

<section class="section">
  <div class="container">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <img src="{{ ingredient.image_url }}" alt="{{ ingredient.name }}">
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4">{{ ingredient.name }}</p>
            <p class="subtitle is-6">{{ ingredient.description }}</p>
          </div>
        </div>

        <div class="content">
          <h5 class="title is-5">Recipes using this ingredient:</h5>
          <ul>
            {% for recipe_ingredient in ingredient.recipeingredient_set.all %}
            <li class="mb-2">
              <a href="{{ recipe_ingredient.recipe.get_absolute_url }}">
                {{ recipe_ingredient.recipe.title }}
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

recipes_app/templates/recipes_app/recipe_confirm_delete.html
{% extends 'recipes_app/base.html' %}


{% block content %}
<div class="conatiner">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <lengend class="border-bootom mb-4">Are you sure you want to delete {{object}} </legend>
            {{ form.as_p }}
        </fieldset>
        <div class="form-group py-3">
            <input type="submit" value="Delete" class="btn btn-outline-danger">
        </div>
    <div class="border-top pt-3">
        <a href="{% url 'recipes-home' %}">Cancel</a>
    </div>

    </form>
</div>
{% endblock content %}

recipes_app/templates/recipes_app/recipe_detail.html
{% extends 'recipes_app/base.html' %} 
{% block content %}

<section class="section">
  <div class="container">
    <h1 class="title" style="text-shadow: 4px 4px 2px rgba(8,209,178,0.58);">{{ recipe.title }}</h1>
    <h4 style="opacity: 0.3; ">Category: {{ recipe.category }}</h4>
    <div class="card">
      <div class="card-image">
        <figure class="image is-4by3">
          <img src="/media/{{ recipe.image }}" alt="Recipe Image">
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="subtitle is-6">{{ recipe.author }} | {{ recipe.created_at }}</p>
          </div>
        </div>

        <div class="content">
          <h5 class="title is-5">Ingredients:</h5>
          <ul>
            {% for ingredient_rel in recipe.recipeingredient_set.all %}
            <li class="mb-2">
              <img src="{{ ingredient_rel.ingredient.image_url }}" alt="{{ ingredient_rel.ingredient.description }}" width="50px" class="mr-2"> 
              <a href="{% url 'ingredient-detail' ingredient_rel.ingredient.pk %}">
                <b>{{ ingredient_rel.ingredient.name }}</b>
              </a>
              <br>
              Quantity: {{ ingredient_rel.quantity }}
              <br>
              Measurement: {{ ingredient_rel.measurement }}
            </li>
            {% endfor %}
          </ul>

          <h5 class="title is-5 mt-3">Directions:</h5>
          <p>{{ recipe.description }}</p>
        </div>

        <div class="buttons mt-4">
          {% if user.is_authenticated %}
            {% if user in recipe.favorited_by.all %}
              <a href="{% url 'unfavorite-recipe' recipe.pk %}" class="button is-danger">Unfavorite</a>
            {% else %}
              <a href="{% url 'favorite-recipe' recipe.pk %}" class="button is-primary">Favorite</a>
            {% endif %}
          {% endif %}

          {% if recipe.author == user or user.is_staff %}
            <a href="{% url 'recipes-update' recipe.id %}" class="button is-link">Edit Recipe</a>
            <a href="{% url 'recipes-delete' recipe.id %}" class="button is-danger">Delete Recipe</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

recipes_app/templates/recipes_app/user_favorites.html
{% extends "recipes_app/base.html" %} 

{% block content %}

<section class="section">
  <div class="container">
    <h2 class="title">Your Favorited Recipes</h2>
    {% if recipes %}
    <div class="columns is-multiline">
      {% for recipe in recipes %}
      <div class="column is-4-widescreen is-6-desktop mb-5">
        <article class="card">
          <div class="card-content">
            <h4 class="title is-4">
              <a href="{% url 'recipes-detail' recipe.pk %}">{{ recipe.title }}</a>
            </h4>
            <a href="{% url 'unfavorite-recipe' recipe.pk %}" class="button is-danger is-small">Unfavorite</a>
          </div>
        </article>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="notification is-warning">
      You haven't favorited any recipes yet. Browse the recipes and favorite some!
    </div>
    {% endif %}
  </div>
</section>

{% endblock %}